### ISSUE TITLE
If I want to set the origin of the chart to (0.5,0.5,0.5) rather than the default(0,0,0), how to do this?

### ISSUE THREAD

**Issue by derekcbr** [Griperis/BlenderDataVis#35]
If I want to set the origin of the chart to (0.5,0.5,0.5) rather than the default(0,0,0), how to do this?

**Comment by Griperis** [comment]
What do you mean by that? Origin of a chart is set to be **blender 3d cursor** (and if the addon can't get value from that, it is [0, 0, 0]),
