### ISSUE TITLE
Exporting in glb/gltf with materials 

### ISSUE THREAD

**Issue by benkates** [Griperis/BlenderDataVis#38]
First off, thank you very much for creating this add-on. We're doing some work in [Spatial](https://spatial.io/) and want to import some data visualizations. This allows us to do that.

I'm new to Blender and having trouble exporting into gltf/glb format with the color included (just getting a white object). I believe I'm including materials in the export but figured I'd ask here as I've had no luck googling. Thanks again/in advance!

**Comment by Griperis** [comment]
Hi, I really like that you are putting it into real use! Firstly if you have any results that are publishable I would really likely put it onto the github page!

Actually the most what I can do for you is to point you the [documentation](https://docs.blender.org/manual/en/2.80/addons/io_scene_gltf2.html) I have never tried exporting to gltf/glb but the materials for the visualisations are quite simple and it should be exportable to anything :(

**Comment by benkates** [comment]
Thanks! I was advised to turn off "Use Nodes" and when rendering an fbx (which Spatial accepts) it rendered with color (although not with glb/gltf) - will continue to keep you updated on this front
