### ISSUE TITLE
Unsoported number of labels on first line (Bubble chart)

### ISSUE THREAD

**Issue by drlztn** [Griperis/BlenderDataVis#39]
Hi,
when I try to animate the size of the bubbles in a bubble chart I get the error _Unsoported number of labels on first line_. In Blender it says this chart needs a XYZW kind of dataset but when I use this for example:

```
x, y, z, w
0, 0, 0, 3, 1, 3.9, 4.2, 4.9
1, 2, 0, 3, 1, 3.9, 4.2, 4.9
0, 2, 4, 3, 1, 3.9, 4.2, 4.9

```
the bubbles won't animate. Does the data have to be different in each bubble? Do you need a minimum number of bubbles?

**Comment by Griperis** [comment]
Hi,
that could be described in a better way, I am sorry for that. 

Actually XYZW kind of dataset doesn't support w label, so if you remove the "w" from the labels it should work.
