### ISSUE TITLE
Is there a sample csv file? I don't know how to write data at all.

### ISSUE THREAD

**Issue by g2mXagent** [Griperis/BlenderDataVis#40]
see above

**Comment by Griperis** [comment]
Hello,

data has to be "clean". Some examples are [here](https://github.com/Griperis/BlenderDataVis#csv-format)

Mainly the supported formats consist of those columns. This is done for a reason, a lot of CSV data is unclear and messy.
**X, Y, Z, (W), (Aditional Z anim)**
Next lines in file are the values, that correspond to the columns respectively. If you have a large CSV file with multiple columns, you can use webapp, that I have made to extract only columns which you want from it [here](https://csv-extractor.herokuapp.com/).

**Comment by g2mXagent** [comment]
Thank you for your reply. I need more detailed examples. 
If you have 6 kinds of charts, there are 6 kinds of CSV formats.
Suppose I want to make a pie chart, do I write it like this?
title1, title2, title3
50%, 30%, 20%

**Comment by Griperis** [comment]
Yeah, I would like to improve the documentation too. This will come with further improvements. But currently I have to study and focus other projects, so I don't have as much time as I would want to do this.

There is actually only one format which varies. If you want to make pie chart you put the values as in this example:
species, occurance
dogs, 5
cats, 10
parrots, 2

Pie chart is great for showing different categories. This will create pie chart consisting of 3 slices each with a size equaled to proportion of the category to overall sum of the occurrence values. Is it more clear?

**Comment by g2mXagent** [comment]
I use this data as input, but the pie chart is grayed out.
[https://imgur.com/ooIsmfM](url)

**Comment by Griperis** [comment]
Try to remove the first line describing the columns, maybe then it will work.

**Comment by g2mXagent** [comment]
it works, thank you
