### ISSUE TITLE
Pie chart not working on blender 2.92

### ISSUE THREAD

**Issue by nitzer** [Griperis/BlenderDataVis#41]
While trying to create a chart using DataVis on Blender 2.92 using a nominal CSV, the pie chart keeps turned grey on the menu impeding to create a pie chart.
Can you tell me if there is anything undocumented step needed to create a pie chart or provide a valid CSV to test?

PD: I love your project and I see some possible scenarios to use it for an internal presentation app if you are interested. 
Thanks.

**Comment by Griperis** [comment]
Hi, I tested it and it should work, can you give an example of nominal csv file you use? Valid CSV are provided on README.md on main page :) 

@nitzer contact me via e-mail (Griperis@outlook.cz) and we can talk if our ends meet :)
