### ISSUE TITLE
Can't add-on to 3.1.2.

### ISSUE THREAD

**Issue by Stevod** [Griperis/BlenderDataVis#50]
When I download the zip, and install it in preferences, it seems to install correctly, and appears in the scripts folder, but does not appear in the list of add-ons (in preferences) that I can search and then enable via a tick-box.

**Comment by Griperis** [comment]
Hi, that is weird, I tested in 3.1 and 3.2 and the addon installs OK. Can you provide further detail?

**Comment by jeffpaletta** [comment]
Also running into this error. I can load the plugin but when I go to Add > Chart > ... all of the options are disabled (greyed out). Experienced this on 3.2.2, 3.1.2, and 3.0.0. Wondering if it's OS related? All of the above were tested on an M1 mac.

**Comment by Griperis** [comment]
@jeffpaletta @LedZep73 did you load any file into the addon, if not the chart operators are blurred by default.

@LedZep73 Created new issue out of this #51 as it is valid. Will be implemented in another update #52
